### ISSUE TITLE
plot error

### ISSUE THREAD

**Issue by fipoucat** [bczernecki/climate#26] opened 2020-02-13 16:00 UTC
Thank for this useful package, trying to replicate your example station from UK on my country but get error and wonder why?:
nearest_stations_ogimet(country = "Senegal",
+                         date = Sys.Date(),
+                         add_map = TRUE,
+                         point = c(-16, 15),
+                         no_of_stations = 100
+ )
Error in plot.window(...) : need finite 'xlim' values
> 

Another question, is it possible to add another country like Gambia which is within Senegal?

**Comment by bczernecki** [comment] 2020-02-13 16:08
Thanks for the feedback! The error is caused by too many stations chosen. Please change the argument add_map = FALSE to see how many stations are available. I will add this improvement in the next package release.

This code below show work if you decrease number of stations to e.g. 10:

`nearest_stations_ogimet(country = "Senegal",
                        date = Sys.Date(),
                        add_map = T,
                        point = c(-16, 15),
                        no_of_stations = 10)
`

If you want to retrieve data for Gambia you can use one of those stations:

`nearest_stations_ogimet(country = "Gamb",
                        date = Sys.Date(),
                        add_map = F,
                        point = c(-16, 15),
                        no_of_stations = 4
)
`

**Comment by fipoucat** [comment] 2020-02-13 16:22
Thank you,worked.
Really great.

**Comment by bczernecki** [comment] 2020-02-15 10:18
bug fixed in climate 0.9.2.

**Closed by bczernecki** 2020-02-15 10:18 UTC
Labels: bug
